services:
  - type: web
    name: arcadia
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - src/**/*.js
        - src/**/*.jsx
        - src/**/*.ts
        - src/**/*.tsx
        - public/**
        - package.json
        - package-lock.json

